# ---------------------------------------------------------------
# Copyright (c) 2021, NVIDIA Corporation. All rights reserved.
#
# This work is licensed under the NVIDIA Source Code License
# ---------------------------------------------------------------
import math
import warnings
import numpy as np
from functools import partial

import torch
import torch.nn as nn
import torch.nn.functional as F


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""
    Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


# --------------------------------------#
#   Gelu激活函数的实现
#   利用近似的数学公式
# --------------------------------------#
class GELU(nn.Module):
    def __init__(self):
        super(GELU, self).__init__()

    def forward(self, x):
        return 0.5 * x * (1 + torch.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * torch.pow(x, 3))))


class OverlapPatchEmbed(nn.Module):
    def __init__(self, patch_size=7, stride=4, in_chans=3, embed_dim=768):
        super().__init__()
        patch_size = (patch_size, patch_size)
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=stride,
                              padding=(patch_size[0] // 2, patch_size[1] // 2))
        self.norm = nn.LayerNorm(embed_dim)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x):
        x = self.proj(x)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)
        x = self.norm(x)

        return x, H, W


# 新增的DWConv和PWConv类
class DWConv(nn.Module):
    def __init__(self, dim=768, kernel_size=3, stride=1, padding=1, dilation=1, bias=True):
        super(DWConv, self).__init__()
        self.dwconv = nn.Conv2d(dim, dim, kernel_size, stride, padding, dilation, bias=bias, groups=dim)

    def forward(self, x):
        x = self.dwconv(x)
        return x


class PWConv(nn.Module):
    def __init__(self, in_channels=768, out_channels=None, bias=True):
        super(PWConv, self).__init__()
        out_channels = out_channels or in_channels
        self.pwconv = nn.Conv2d(in_channels, out_channels, 1, bias=bias)

    def forward(self, x):
        x = self.pwconv(x)
        return x


# 新增的SLAK大核注意力模块
class SLAK(nn.Module):
    """SLAK大核注意力模块 - 优化版本"""

    def __init__(self, dim, kernel_size=51):
        super().__init__()
        self.dim = dim

        # 对于大kernel_size，使用分解卷积减少计算量
        if kernel_size > 31:
            # 使用两个连续的卷积来近似大核卷积
            self.conv_small = DWConv(dim, kernel_size=5, padding=2)
            self.conv_big_h = nn.Sequential(
                DWConv(dim, kernel_size=(1, kernel_size), padding=(0, kernel_size // 2)),
                DWConv(dim, kernel_size=(kernel_size, 1), padding=(kernel_size // 2, 0))
            )
            self.conv_big_v = nn.Sequential(
                DWConv(dim, kernel_size=(kernel_size, 1), padding=(kernel_size // 2, 0)),
                DWConv(dim, kernel_size=(1, kernel_size), padding=(0, kernel_size // 2))
            )
        else:
            # 直接使用大核卷积
            self.conv_small = DWConv(dim, kernel_size=5, padding=2)
            self.conv_big_h = DWConv(dim, kernel_size=(kernel_size, 5),
                                     padding=(kernel_size // 2, 2))
            self.conv_big_v = DWConv(dim, kernel_size=(5, kernel_size),
                                     padding=(2, kernel_size // 2))

        self.pwconv = PWConv(dim, dim)

        # 初始化权重
        self._initialize_weights()

    def _initialize_weights(self):
        # 简化的权重初始化
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, x):
        u = x.clone()  # 保存原始特征

        # 多尺度特征提取
        attn_small = self.conv_small(x)
        attn_big_h = self.conv_big_h(x)
        attn_big_v = self.conv_big_v(x)

        # 特征融合
        attn = attn_small + attn_big_h + attn_big_v
        attn = self.pwconv(attn)

        # 使用sigmoid确保注意力权重在合理范围内
        attn = torch.sigmoid(attn)

        # 注意力机制：增强重要特征
        return u * attn


# 新增的可学习的边缘感知模块
class LearnableEdgeAwareModule(nn.Module):
    """可学习的边缘感知模块"""

    def __init__(self, in_channels):
        super().__init__()

        # 可学习的多尺度特征差异检测
        self.diff_conv = nn.Sequential(
            DWConv(in_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(in_channels),
            nn.ReLU(inplace=True)
        )

        # 特征增强门控
        self.gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            PWConv(in_channels, max(4, in_channels // 16)),
            nn.ReLU(),
            PWConv(max(4, in_channels // 16), in_channels),
            nn.Sigmoid()
        )

        self._initialize_weights()

    def _initialize_weights(self):
        # 初始化DWConv
        nn.init.normal_(self.diff_conv[0].dwconv.weight, 0, 0.01)
        if self.diff_conv[0].dwconv.bias is not None:
            nn.init.constant_(self.diff_conv[0].dwconv.bias, 0)

        # 初始化PWConv
        nn.init.normal_(self.gate[1].pwconv.weight, 0, 0.01)
        nn.init.normal_(self.gate[3].pwconv.weight, 0, 0.01)
        if self.gate[3].pwconv.bias is not None:
            nn.init.constant_(self.gate[3].pwconv.bias, 0.0)  # sigmoid(0)=0.5

    def forward(self, x):
        # 计算特征变化
        feature_diff = self.diff_conv(x)

        # 学习何时增强边界特征
        gate_weights = self.gate(x)

        # 自适应增强
        enhanced = x + feature_diff * gate_weights

        return enhanced


# 原始的Attention模块（保留用于集成注意力）
class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0., sr_ratio=1):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."

        self.dim = dim
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.q = nn.Linear(dim, dim, bias=qkv_bias)

        self.sr_ratio = sr_ratio
        if sr_ratio > 1:
            self.sr = nn.Conv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
            self.norm = nn.LayerNorm(dim)
        self.kv = nn.Linear(dim, dim * 2, bias=qkv_bias)

        self.attn_drop = nn.Dropout(attn_drop)

        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        B, N, C = x.shape
        # bs, 16384, 32 => bs, 16384, 32 => bs, 16384, 8, 4 => bs, 8, 16384, 4
        q = self.q(x).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)

        if self.sr_ratio > 1:
            # bs, 16384, 32 => bs, 32, 128, 128
            x_ = x.permute(0, 2, 1).reshape(B, C, H, W)
            # bs, 32, 128, 128 => bs, 32, 16, 16 => bs, 256, 32
            x_ = self.sr(x_).reshape(B, C, -1).permute(0, 2, 1)
            x_ = self.norm(x_)
            # bs, 256, 32 => bs, 256, 64 => bs, 256, 2, 8, 4 => 2, bs, 8, 256, 4
            kv = self.kv(x_).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        else:
            kv = self.kv(x).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        k, v = kv[0], kv[1]

        # bs, 8, 16384, 4 @ bs, 8, 4, 256 => bs, 8, 16384, 256
        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        # bs, 8, 16384, 256  @ bs, 8, 256, 4 => bs, 8, 16384, 4 => bs, 16384, 32
        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        # bs, 16384, 32 => bs, 16384, 32
        x = self.proj(x)
        x = self.proj_drop(x)

        return x


# 新增的集成注意力模块
class IntegratedAttention(nn.Module):
    """集成注意力模块 - 使用SLAK大核注意力"""

    def __init__(self, dim, num_heads=8, sr_ratio=1,
                 use_edge_attention=True, use_large_kernel=True,
                 kernel_size=51):
        super().__init__()

        # 原始SegFormer注意力
        self.original_attn = Attention(
            dim, num_heads=num_heads, qkv_bias=True,
            attn_drop=0.1, proj_drop=0.1, sr_ratio=sr_ratio
        )

        # 边缘感知模块
        self.use_edge_attention = use_edge_attention
        if use_edge_attention:
            self.edge_attention = LearnableEdgeAwareModule(dim)
            self.edge_alpha = nn.Parameter(torch.tensor(0.5))

        # SLAK大核注意力
        self.use_large_kernel = use_large_kernel
        if use_large_kernel:
            self.large_kernel_attn = SLAK(dim, kernel_size=kernel_size)
            self.kernel_alpha = nn.Parameter(torch.tensor(0.5))
#特征融合门控机制，修复维度问题
        self.num_attentions = 1  # 原始注意力
        if use_edge_attention:
            self.num_attentions += 1
        if use_large_kernel:
            self.num_attentions += 1

        if self.num_attentions > 1:
            self.fusion_gate = nn.Sequential(
                nn.Linear(dim * self.num_attentions, max(4, dim // 4)),
                nn.ReLU(),
                nn.Linear(max(4, dim // 4), self.num_attentions),
                nn.Softmax(dim=-1)
            )

    def forward(self, x, H, W):
        B, N, C = x.shape

        # 原始注意力
        original_out = self.original_attn(x, H, W)

        # 转换为2D特征进行处理
        x_2d = x.reshape(B, H, W, C).permute(0, 3, 1, 2)
        original_2d = original_out.reshape(B, H, W, C).permute(0, 3, 1, 2)

        # 收集所有注意力特征
        attention_features = [original_2d]

        # 边缘感知增强
        if self.use_edge_attention:
            edge_enhanced = self.edge_attention(original_2d)
            attention_features.append(edge_enhanced)

        # SLAK大核注意力增强
        if self.use_large_kernel:
            kernel_enhanced = self.large_kernel_attn(original_2d)
            attention_features.append(kernel_enhanced)

        # 智能特征融合
        if len(attention_features) == 1:
            fused_2d = original_2d
        elif len(attention_features) == 2:
            if self.use_edge_attention:
                alpha = torch.sigmoid(self.edge_alpha)
                fused_2d = alpha * edge_enhanced + (1 - alpha) * original_2d
            else:
                alpha = torch.sigmoid(self.kernel_alpha)
                fused_2d = alpha * kernel_enhanced + (1 - alpha) * original_2d
        else:
            # 三种注意力，使用门控机制 - 修复维度问题
            pooled_features = []
            for feat in attention_features:
                pooled = F.adaptive_avg_pool2d(feat, 1).view(B, C)  # [B, C]
                pooled_features.append(pooled)

            pooled_concat = torch.cat(pooled_features, dim=-1)  # [B, C * num_attentions]
            weights = self.fusion_gate(pooled_concat)  # [B, num_attentions]

            # 调整权重维度以匹配特征图
            weights = weights.view(B, self.num_attentions, 1, 1, 1)  # [B, num_attentions, 1, 1, 1]
            stacked_features = torch.stack(attention_features, dim=1)  # [B, num_attentions, C, H, W]

            # 应用权重并求和
            fused_2d = (stacked_features * weights).sum(dim=1)  # [B, C, H, W]

        # 转换回序列格式
        fused_out = fused_2d.permute(0, 2, 3, 1).reshape(B, N, C)

        return fused_out


def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    """
    Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor


class DropPath(nn.Module):
    def __init__(self, drop_prob=None, scale_by_keep=True):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)


class DWConv_old(nn.Module):
    def __init__(self, dim=768):
        super(DWConv_old, self).__init__()
        self.dwconv = nn.Conv2d(dim, dim, 3, 1, 1, bias=True, groups=dim)

    def forward(self, x, H, W):
        B, N, C = x.shape
        x = x.transpose(1, 2).view(B, C, H, W)
        x = self.dwconv(x)
        x = x.flatten(2).transpose(1, 2)

        return x


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features

        self.fc1 = nn.Linear(in_features, hidden_features)
        self.dwconv = DWConv_old(hidden_features)
        self.act = act_layer()

        self.fc2 = nn.Linear(hidden_features, out_features)

        self.drop = nn.Dropout(drop)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        x = self.fc1(x)
        x = self.dwconv(x, H, W)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


# 改进的Block，使用集成注意力
class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=GELU, norm_layer=nn.LayerNorm, sr_ratio=1,
                 use_edge_attention=True, use_large_kernel=True, kernel_size=51):
        super().__init__()
        self.norm1 = norm_layer(dim)

        # 使用集成注意力模块替换原始注意力
        self.attn = IntegratedAttention(
            dim, num_heads=num_heads, sr_ratio=sr_ratio,
            use_edge_attention=use_edge_attention,
            use_large_kernel=use_large_kernel,
            kernel_size=kernel_size
        )
        self.norm2 = norm_layer(dim)
        self.mlp = Mlp(in_features=dim, hidden_features=int(dim * mlp_ratio), act_layer=act_layer, drop=drop)

        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))
        return x


class MixVisionTransformer(nn.Module):
    def __init__(self, in_chans=3, num_classes=1000, embed_dims=[32, 64, 160, 256],
                 num_heads=[1, 2, 4, 8], mlp_ratios=[4, 4, 4, 4], qkv_bias=False, qk_scale=None, drop_rate=0.,
                 attn_drop_rate=0., drop_path_rate=0., norm_layer=nn.LayerNorm,
                 depths=[3, 4, 6, 3], sr_ratios=[8, 4, 2, 1],
                 use_edge_attention=[True, True, True, True],
                 use_large_kernel=[False, True, True, True],
                 kernel_sizes=[31, 51, 51, 51]):
        super().__init__()
        self.num_classes = num_classes
        self.depths = depths

        # ----------------------------------#
        #   Transformer模块，共有四个部分
        # ----------------------------------#
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]

        # ----------------------------------#
        #   block1
        # ----------------------------------#
        # -----------------------------------------------#
        #   对输入图像进行分区，并下采样
        #   512, 512, 3 => 128, 128, 32 => 16384, 32
        # -----------------------------------------------#
        self.patch_embed1 = OverlapPatchEmbed(patch_size=7, stride=4, in_chans=in_chans, embed_dim=embed_dims[0])
        # -----------------------------------------------#
        #   利用transformer模块进行特征提取
        #   16384, 32 => 16384, 32
        # -----------------------------------------------#
        cur = 0
        self.block1 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[0], num_heads=num_heads[0], mlp_ratio=mlp_ratios[0], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[0],
                    use_edge_attention=use_edge_attention[0], use_large_kernel=use_large_kernel[0],
                    kernel_size=kernel_sizes[0]
                )
                for i in range(depths[0])
            ]
        )
        self.norm1 = norm_layer(embed_dims[0])

        # ----------------------------------#
        #   block2
        # ----------------------------------#
        # -----------------------------------------------#
        #   对输入图像进行分区，并下采样
        #   128, 128, 32 => 64, 64, 64 => 4096, 64
        # -----------------------------------------------#
        self.patch_embed2 = OverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[0], embed_dim=embed_dims[1])
        # -----------------------------------------------#
        #   利用transformer模块进行特征提取
        #   4096, 64 => 4096, 64
        # -----------------------------------------------#
        cur += depths[0]
        self.block2 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[1], num_heads=num_heads[1], mlp_ratio=mlp_ratios[1], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[1],
                    use_edge_attention=use_edge_attention[1], use_large_kernel=use_large_kernel[1],
                    kernel_size=kernel_sizes[1]
                )
                for i in range(depths[1])
            ]
        )
        self.norm2 = norm_layer(embed_dims[1])

        # ----------------------------------#
        #   block3
        # ----------------------------------#
        # -----------------------------------------------#
        #   对输入图像进行分区，并下采样
        #   64, 64, 64 => 32, 32, 160 => 1024, 160
        # -----------------------------------------------#
        self.patch_embed3 = OverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[1], embed_dim=embed_dims[2])
        # -----------------------------------------------#
        #   利用transformer模块进行特征提取
        #   1024, 160 => 1024, 160
        # -----------------------------------------------#
        cur += depths[1]
        self.block3 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[2], num_heads=num_heads[2], mlp_ratio=mlp_ratios[2], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[2],
                    use_edge_attention=use_edge_attention[2], use_large_kernel=use_large_kernel[2],
                    kernel_size=kernel_sizes[2]
                )
                for i in range(depths[2])
            ]
        )
        self.norm3 = norm_layer(embed_dims[2])

        # ----------------------------------#
        #   block4
        # ----------------------------------#
        # -----------------------------------------------#
        #   对输入图像进行分区，并下采样
        #   32, 32, 160 => 16, 16, 256 => 256, 256
        # -----------------------------------------------#
        self.patch_embed4 = OverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[2], embed_dim=embed_dims[3])
        # -----------------------------------------------#
        #   利用transformer模块进行特征提取
        #   256, 256 => 256, 256
        # -----------------------------------------------#
        cur += depths[2]
        self.block4 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[3], num_heads=num_heads[3], mlp_ratio=mlp_ratios[3], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[3],
                    use_edge_attention=use_edge_attention[3], use_large_kernel=use_large_kernel[3],
                    kernel_size=kernel_sizes[3]
                )
                for i in range(depths[3])
            ]
        )
        self.norm4 = norm_layer(embed_dims[3])

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x):
        B = x.shape[0]
        outs = []

        # ----------------------------------#
        #   block1
        # ----------------------------------#
        x, H, W = self.patch_embed1.forward(x)
        for i, blk in enumerate(self.block1):
            x = blk.forward(x, H, W)
        x = self.norm1(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # ----------------------------------#
        #   block2
        # ----------------------------------#
        x, H, W = self.patch_embed2.forward(x)
        for i, blk in enumerate(self.block2):
            x = blk.forward(x, H, W)
        x = self.norm2(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # ----------------------------------#
        #   block3
        # ----------------------------------#
        x, H, W = self.patch_embed3.forward(x)
        for i, blk in enumerate(self.block3):
            x = blk.forward(x, H, W)
        x = self.norm3(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # ----------------------------------#
        #   block4
        # ----------------------------------#
        x, H, W = self.patch_embed4.forward(x)
        for i, blk in enumerate(self.block4):
            x = blk.forward(x, H, W)
        x = self.norm4(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        return outs


# 预定义配置 - 使用集成注意力
class mit_b0_improved(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b0_improved, self).__init__(
            embed_dims=[32, 64, 160, 256], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[2, 2, 2, 2], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1,
            use_edge_attention=[True, True, True, True],
            use_large_kernel=[False, True, True, True],
            kernel_sizes=[31, 51, 51, 51]
        )
        if pretrained:
            print("Load backbone weights")
            self._load_pretrained("model_data/segformer_b0_backbone_weights.pth")


class mit_b1_improved(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b1_improved, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[2, 2, 2, 2], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1,
            use_edge_attention=[True, True, True, True],
            use_large_kernel=[False, True, True, True],
            kernel_sizes=[31, 51, 51, 51]
        )
        if pretrained:
            print("Load backbone weights")
            self._load_pretrained("model_data/segformer_b1_backbone_weights.pth")


class mit_b2_improved(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b2_improved, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 4, 6, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1,
            use_edge_attention=[True, True, True, True],
            use_large_kernel=[False, True, True, True],
            kernel_sizes=[31, 51, 51, 51]
        )
        if pretrained:
            print("Load backbone weights")
            self._load_pretrained("model_data/segformer_b2_backbone_weights.pth")


class mit_b3_improved(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b3_improved, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 4, 18, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1,
            use_edge_attention=[True, True, True, True],
            use_large_kernel=[False, True, True, True],
            kernel_sizes=[31, 51, 51, 51]
        )
        if pretrained:
            print("Load backbone weights")
            self._load_pretrained("model_data/segformer_b3_backbone_weights.pth")


class mit_b4_improved(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b4_improved, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 8, 27, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1,
            use_edge_attention=[True, True, True, True],
            use_large_kernel=[False, True, True, True],
            kernel_sizes=[31, 51, 51, 51]
        )
        if pretrained:
            print("Load backbone weights")
            self._load_pretrained("model_data/segformer_b4_backbone_weights.pth")


class mit_b5_improved(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b5_improved, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 6, 40, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1,
            use_edge_attention=[True, True, True, True],
            use_large_kernel=[False, True, True, True],
            kernel_sizes=[31, 51, 51, 51]
        )
        if pretrained:
            print("Load backbone weights")
            self._load_pretrained("model_data/segformer_b5_backbone_weights.pth")

    def _load_pretrained(self, weight_path):
        try:
            print(f"Loading pretrained weights from {weight_path}")
            state_dict = torch.load(weight_path, map_location='cpu')
            model_state_dict = self.state_dict()
            filtered_state_dict = {}

            for k, v in state_dict.items():
                if k in model_state_dict and v.shape == model_state_dict[k].shape:
                    if all(x not in k for x in
                           ['integrated_attn', 'edge_attention', 'large_kernel_attn', 'fusion_gate']):
                        filtered_state_dict[k] = v

            self.load_state_dict(filtered_state_dict, strict=False)
            print(f"Loaded {len(filtered_state_dict)}/{len(state_dict)} parameters")
        except Exception as e:
            print(f"Error loading pretrained weights: {e}")


# 保留原始版本以保持兼容性
class mit_b0(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b0, self).__init__(
            embed_dims=[32, 64, 160, 256], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[2, 2, 2, 2], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1
        )
        if pretrained:
            print("Load backbone weights")
            self.load_state_dict(torch.load("model_data/segformer_b0_backbone_weights.pth"), strict=False)


class mit_b1(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b1, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[2, 2, 2, 2], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1
        )
        if pretrained:
            print("Load backbone weights")
            self.load_state_dict(torch.load("model_data/segformer_b1_backbone_weights.pth"), strict=False)


class mit_b2(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b2, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 4, 6, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1
        )
        if pretrained:
            print("Load backbone weights")
            self.load_state_dict(torch.load("model_data/segformer_b2_backbone_weights.pth"), strict=False)


class mit_b3(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b3, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 4, 18, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1
        )
        if pretrained:
            print("Load backbone weights")
            self.load_state_dict(torch.load("model_data/segformer_b3_backbone_weights.pth"), strict=False)


class mit_b4(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b4, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 8, 27, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1
        )
        if pretrained:
            print("Load backbone weights")
            self.load_state_dict(torch.load("model_data/segformer_b4_backbone_weights.pth"), strict=False)


class mit_b5(MixVisionTransformer):
    def __init__(self, pretrained=False):
        super(mit_b5, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 6, 40, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1
        )
        if pretrained:
            print("Load backbone weights")
            self.load_state_dict(torch.load("model_data/segformer_b5_backbone_weights.pth"), strict=False)